### ISSUE TITLE
ConcurrentModificationException occurs very often when trying to mutate the value

### ISSUE THREAD

**Issue by TE-PreetamBhosle** [RomanPozdeev/MobX#2]
ConcurrentModificationException occurs when the observable value is modified and at the same time, it is access on UI OR in observeChanges({  }) function.

This library can't be used in adapters with too many items and the items are being changed frequently. 

@RomanPozdeev

**Comment by RomanPozdeev** [comment]
If you send a link to an example where this problem is reproduced, it will be much easier to fix

**Comment by TE-PreetamBhosle** [comment]
> If you send a link to an example where this problem is reproduced, it will be much easier to fix

Thanks for responding. I'll create an example and give a link here.

**Comment by aryapreetam** [comment]
@RomanPozdeev 
please find the example to reproduce error here https://github.com/preetb123/mobxcmeerrorexample


I have added video also https://www.veed.io/view/b08bc376-4ca8-40b8-8d40-79433423599a?panel=share

**Comment by RomanPozdeev** [comment]
Thanks for example.

If you are changing the state of a store from multiple threads, you need to ensure synchronization. The current implementation is not thread safe.

This was done to ensure maximum performance.

**Comment by aryapreetam** [comment]
@RomanPozdeev 
Can you please give an example on how can I make it threadsafe?

**Comment by RomanPozdeev** [comment]
I would recommend using only the main thread in the store. For example:

```kotlin
class TestStore {
  var count by observable(0)
    private set

  fun incCount() {
    ThreadUtils.runOnUiThread {
      action {
        count += 1
      }
    }
  }

  fun decCount() {
    ThreadUtils.runOnUiThread {
      action {
        count -= 1
      }
    }
  }
}

object ThreadUtils {
  private val handler = Handler(Looper.getMainLooper())
  fun runOnUiThread(action: Runnable) {
    if (Looper.getMainLooper().thread === Thread.currentThread()) {
      action.run()
    } else {
      handler.post(action)
    }
  }
}
```

**Comment by TE-PreetamBhosle** [comment]
@RomanPozdeev 
Not sure if approach recommended by you will work because I had done something similar where I used to execute every action as below

```kotlin
fun update(function: () -> Unit) {
  Handler(Looper.getMainLooper()).post(Runnable {
    function()
  })
}

// this will be used as below
update { stateStore.toggleMicStatus() }

// toggleMicStatus
fun toggleMicStatus() = action("TOGGLE_MIC_STATUS") {
  micStatus = !micStatus
}
```

**Comment by TE-PreetamBhosle** [comment]
I am a big fan of `mobx` and `mobx-state-tree` & really appreciate your efforts for building this lib. 
If you can help & guide me, I'll try to create a thread-safe version of this lib.

**Comment by TE-PreetamBhosle** [comment]
> I would recommend using only the main thread in the store. For example:
> 
> ```kotlin
> class TestStore {
>   var count by observable(0)
>     private set
> 
>   fun incCount() {
>     ThreadUtils.runOnUiThread {
>       action {
>         count += 1
>       }
>     }
>   }
> 
>   fun decCount() {
>     ThreadUtils.runOnUiThread {
>       action {
>         count -= 1
>       }
>     }
>   }
> }
> 
> object ThreadUtils {
>   private val handler = Handler(Looper.getMainLooper())
>   fun runOnUiThread(action: Runnable) {
>     if (Looper.getMainLooper().thread === Thread.currentThread()) {
>       action.run()
>     } else {
>       handler.post(action)
>     }
>   }
> }
> ```

This solution works well with the example in this repo.
